spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: A1991a++
  jpa:
    database : mysql
    show_database : true

    hibernate:
      ddl-auto: create

      jackson:
        serialization:
          fail-on-empty-beans: false
